# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c109b29a16e3e174e8e5440b1089b2f8f9b6b2217c34d2083ab4d8af136b214657a8816354c09a07089fd37e6e91e63685be48d195cfe83742c0520743bb79b

test:
  secret_key_base: 8c10749051f8752f78dbd68d44f4f999afd9ef75f7a15b221cfad7ecab4a82f4da09ca6183943a8ed088a3f3ffd53ef458643442879e542394ba34917e991a48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
